data:
  bounding_box: 0.7
  coarse_grid_spacing: 0.04375
  dataset: sunrgbd
  marching_cube_resolution: 128
  mask: false
  split: data/sunrgbd/splits
demo:
  phase: joint
device:
  gpu_ids: '0'
  num_workers: 4
  use_gpu: true
finetune: true
log:
  path: out/pretrained_models/total3d
  print_step: 50
  save_results: true
  # vis_path: out/total3d/20110611514267/visualization
  vis_step: 100
loss_weights:
  bdb2D_loss: 0.75
  centroid_cls_loss: 0.75
  centroid_reg_loss: 0.5
  corner_loss: 0.75
  ldif_phy_loss: 20.0
  lo_centroid_loss: 1.0
  lo_coeffs_loss: 1.0
  lo_corner_loss: 1.0
  lo_ori_cls_loss: 0.25
  lo_ori_reg_loss: 0.75
  mesh_loss: 0.0
  offset_2D_loss: 0.5
  ori_cls_loss: 0.33
  ori_reg_loss: 1.0
  phy_loss: 0.75
  pitch_cls_loss: 0.25
  pitch_reg_loss: 1.0
  roll_cls_loss: 0.25
  roll_reg_loss: 0.5
  size_reg_loss: 1.0
method: TOTAL3D
model:
  layout_estimation:
    loss: PoseLoss
    method: PoseNet
  mesh_reconstruction:
    bottleneck_size: 1536
    center_coef_estimate: blob
    element_count: 32
    implicit_parameter_length: 32
    loss: LDIFReconLoss
    loss_settings:
      phy_loss_objects: 4
      phy_loss_samples: 128
      scale_before_func: 100.0
      surface_optimize: true
      type: classmse
    method: LDIF
    object_samples: 512
    scale_fac: 1.0
    sym_element_count: 16
  object_detection:
    loss: DetLoss
    method: Bdb3DNet
  output_adjust:
    feat_update_step: 4
    feature_dim: 512
    lo_features:
    - pitch_reg_result
    - roll_reg_result
    - pitch_cls_result
    - roll_cls_result
    - lo_ori_reg_result
    - lo_ori_cls_result
    - lo_centroid_result
    - lo_coeffs_result
    - lo_afeatures
    - K
    loss: null
    method: GCNN
    obj_features:
    - size_cls
    - cls_codes
    - size_reg_result
    - ori_reg_result
    - ori_cls_result
    - centroid_reg_result
    - centroid_cls_result
    - offset_2D_result
    - analytic_code
    - odn_arfeatures
    - blob_center
    rel_features:
    - g_features
    - bdb2D_pos
    res_output: true
optimizer:
  betas:
  - 0.9
  - 0.999
  eps: 1e-08
  lr: 1e-4
  method: Adam
  weight_decay: 1e-04
resume: false
scheduler:
  gamma: 0.5
  method: MultiStepLR
  milestones:
  - 18
  - 23
  - 28
seed: 123
test:
  batch_size: 1
  phase: joint
train:
  batch_size: 2
  epochs: 30
  freeze:
  - mesh_reconstruction
  phase: joint
val:
  batch_size: 1
  phase: joint
weight: out/total3d/20110611514267/model_best.pth
